rectangle|filled|3|2
rectangle|filled|20|7
rectangle|hollow|3|2
rectangle|hollow|20|7
rectangle|alternating|20|3
rectangle|alternating|20|5
triangle|left|3
triangle|left|6
triangle|right|3
triangle|right|6
diamond|filled|5
diamond|filled|7
diamond|hollow|5
diamond|hollow|7
diamond|angled|5
diamond|angled|7
